// <auto-generated />
using AzureFunc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FunctionsFinal.Data.Migrations
{
    [DbContext(typeof(NhlContext))]
    [Migration("20220420192826_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AzureFunc.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("From")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasColumnType("longtext");

                    b.HasKey("PlayerId");

                    b.ToTable("Player", (string)null);

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Age = 24,
                            FirstName = "Connor",
                            From = "Canada",
                            LastName = "McDavid",
                            Position = "F",
                            Rank = 1,
                            Team = "EDM"
                        },
                        new
                        {
                            PlayerId = 2,
                            Age = 26,
                            FirstName = "Leon",
                            From = "Germany",
                            LastName = "Draisaitl",
                            Position = "F",
                            Rank = 2,
                            Team = "EDM"
                        },
                        new
                        {
                            PlayerId = 3,
                            Age = 28,
                            FirstName = "Jonathan",
                            From = "Canada",
                            LastName = "Huberdeau",
                            Position = "F",
                            Rank = 3,
                            Team = "FLA"
                        },
                        new
                        {
                            PlayerId = 4,
                            Age = 28,
                            FirstName = "Johnny",
                            From = "USA",
                            LastName = "Gaudreau",
                            Position = "F",
                            Rank = 4,
                            Team = "CGY"
                        },
                        new
                        {
                            PlayerId = 5,
                            Age = 24,
                            FirstName = "Auston",
                            From = "USA",
                            LastName = "Matthews",
                            Position = "F",
                            Rank = 5,
                            Team = "TOR"
                        },
                        new
                        {
                            PlayerId = 6,
                            Age = 24,
                            FirstName = "Kirill",
                            From = "Russia",
                            LastName = "Kaprizov",
                            Position = "F",
                            Rank = 6,
                            Team = "MIN"
                        },
                        new
                        {
                            PlayerId = 7,
                            Age = 24,
                            FirstName = "Matthew",
                            From = "USA",
                            LastName = "Tkachuk",
                            Position = "F",
                            Rank = 7,
                            Team = "CGY"
                        },
                        new
                        {
                            PlayerId = 8,
                            Age = 31,
                            FirstName = "Nazem",
                            From = "Canada",
                            LastName = "Kadri",
                            Position = "F",
                            Rank = 8,
                            Team = "COL"
                        },
                        new
                        {
                            PlayerId = 9,
                            Age = 25,
                            FirstName = "Kyle",
                            From = "USA",
                            LastName = "Connor",
                            Position = "F",
                            Rank = 9,
                            Team = "WPG"
                        },
                        new
                        {
                            PlayerId = 10,
                            Age = 25,
                            FirstName = "Mikko",
                            From = "Finland",
                            LastName = "Rantanen",
                            Position = "F",
                            Rank = 10,
                            Team = "COL"
                        },
                        new
                        {
                            PlayerId = 11,
                            Age = 24,
                            FirstName = "Mitchell",
                            From = "Canada",
                            LastName = "Marner",
                            Position = "F",
                            Rank = 11,
                            Team = "TOR"
                        },
                        new
                        {
                            PlayerId = 12,
                            Age = 28,
                            FirstName = "J.T. ",
                            From = "USA",
                            LastName = "Miller",
                            Position = "F",
                            Rank = 12,
                            Team = "VAN"
                        },
                        new
                        {
                            PlayerId = 13,
                            Age = 31,
                            FirstName = "Roman",
                            From = "Switzerland",
                            LastName = "Josi",
                            Position = "D",
                            Rank = 13,
                            Team = "NSH"
                        },
                        new
                        {
                            PlayerId = 14,
                            Age = 30,
                            FirstName = "Artemi",
                            From = "Russia",
                            LastName = "Panarin",
                            Position = "F",
                            Rank = 14,
                            Team = "NYR"
                        },
                        new
                        {
                            PlayerId = 15,
                            Age = 33,
                            FirstName = "Patrick",
                            From = "USA",
                            LastName = "Kane",
                            Position = "F",
                            Rank = 15,
                            Team = "CHI"
                        },
                        new
                        {
                            PlayerId = 16,
                            Age = 36,
                            FirstName = "Alexander",
                            From = "Russia",
                            LastName = "Ovechkin",
                            Position = "F",
                            Rank = 16,
                            Team = "WSH"
                        },
                        new
                        {
                            PlayerId = 17,
                            Age = 31,
                            FirstName = "Steven",
                            From = "Canada",
                            LastName = "Stamkos",
                            Position = "F",
                            Rank = 17,
                            Team = "TBL"
                        },
                        new
                        {
                            PlayerId = 18,
                            Age = 23,
                            FirstName = "Cale",
                            From = "Canada",
                            LastName = "Makar",
                            Position = "D",
                            Rank = 18,
                            Team = "COL"
                        },
                        new
                        {
                            PlayerId = 19,
                            Age = 34,
                            FirstName = "Sidney",
                            From = "Canada",
                            LastName = "Crosby",
                            Position = "F",
                            Rank = 19,
                            Team = "PIT"
                        },
                        new
                        {
                            PlayerId = 20,
                            Age = 26,
                            FirstName = "Nathan",
                            From = "Canada",
                            LastName = "MacKinnon",
                            Position = "F",
                            Rank = 20,
                            Team = "COL"
                        },
                        new
                        {
                            PlayerId = 21,
                            Age = 25,
                            FirstName = "David",
                            From = "Czeck Republic",
                            LastName = "Pastrnak",
                            Position = "F",
                            Rank = 21,
                            Team = "BOS"
                        },
                        new
                        {
                            PlayerId = 22,
                            Age = 33,
                            FirstName = "Brad",
                            From = "Canada",
                            LastName = "Marchand",
                            Position = "F",
                            Rank = 22,
                            Team = "BOS"
                        },
                        new
                        {
                            PlayerId = 23,
                            Age = 30,
                            FirstName = "Matt",
                            From = "Canada",
                            LastName = "Duchene",
                            Position = "F",
                            Rank = 23,
                            Team = "NSH"
                        },
                        new
                        {
                            PlayerId = 24,
                            Age = 26,
                            FirstName = "Aleksander",
                            From = "Finland",
                            LastName = "Barkov",
                            Position = "F",
                            Rank = 24,
                            Team = "FLA"
                        },
                        new
                        {
                            PlayerId = 25,
                            Age = 28,
                            FirstName = "Mika",
                            From = "Sweden",
                            LastName = "Zibanejad",
                            Position = "F",
                            Rank = 25,
                            Team = "NYR"
                        },
                        new
                        {
                            PlayerId = 26,
                            Age = 27,
                            FirstName = "Elias",
                            From = "Sweden",
                            LastName = "Lindholm",
                            Position = "F",
                            Rank = 26,
                            Team = "CGY"
                        },
                        new
                        {
                            PlayerId = 27,
                            Age = 24,
                            FirstName = "Sebastian",
                            From = "Finland",
                            LastName = "Aho",
                            Position = "F",
                            Rank = 27,
                            Team = "CAR"
                        },
                        new
                        {
                            PlayerId = 28,
                            Age = 34,
                            FirstName = "Mats",
                            From = "Norway",
                            LastName = "Zuccarello",
                            Position = "F",
                            Rank = 28,
                            Team = "MIN"
                        },
                        new
                        {
                            PlayerId = 29,
                            Age = 27,
                            FirstName = "Jake",
                            From = "USA",
                            LastName = "Guentzel",
                            Position = "F",
                            Rank = 29,
                            Team = "PIT"
                        },
                        new
                        {
                            PlayerId = 30,
                            Age = 37,
                            FirstName = "Joe",
                            From = "USA",
                            LastName = "Pavelski",
                            Position = "F",
                            Rank = 30,
                            Team = "DAL"
                        },
                        new
                        {
                            PlayerId = 31,
                            Age = 27,
                            FirstName = "Filip",
                            From = "Sweden",
                            LastName = "Forsberg",
                            Position = "F",
                            Rank = 31,
                            Team = "NSH"
                        },
                        new
                        {
                            PlayerId = 32,
                            Age = 25,
                            FirstName = "Timo",
                            From = "Switzerland",
                            LastName = "Meier",
                            Position = "F",
                            Rank = 32,
                            Team = "SJS"
                        },
                        new
                        {
                            PlayerId = 33,
                            Age = 31,
                            FirstName = "Victor",
                            From = "Sweden",
                            LastName = "Hedman",
                            Position = "D",
                            Rank = 33,
                            Team = "TBL"
                        },
                        new
                        {
                            PlayerId = 34,
                            Age = 23,
                            FirstName = "Adam",
                            From = "USA",
                            LastName = "Fox",
                            Position = "D",
                            Rank = 34,
                            Team = "NYR"
                        },
                        new
                        {
                            PlayerId = 35,
                            Age = 30,
                            FirstName = "Chris",
                            From = "USA",
                            LastName = "Kreider",
                            Position = "F",
                            Rank = 35,
                            Team = "NYR"
                        },
                        new
                        {
                            PlayerId = 36,
                            Age = 24,
                            FirstName = "Alex",
                            From = "USA",
                            LastName = "DeBrincat",
                            Position = "F",
                            Rank = 36,
                            Team = "CHI"
                        },
                        new
                        {
                            PlayerId = 37,
                            Age = 28,
                            FirstName = "Mark",
                            From = "Canada",
                            LastName = "Scheifele",
                            Position = "F",
                            Rank = 37,
                            Team = "WPG"
                        },
                        new
                        {
                            PlayerId = 38,
                            Age = 26,
                            FirstName = "Sam",
                            From = "Canada",
                            LastName = "Reinhart",
                            Position = "F",
                            Rank = 38,
                            Team = "FLA"
                        },
                        new
                        {
                            PlayerId = 39,
                            Age = 31,
                            FirstName = "John",
                            From = "Canada",
                            LastName = "Tavares",
                            Position = "F",
                            Rank = 39,
                            Team = "TOR"
                        },
                        new
                        {
                            PlayerId = 40,
                            Age = 23,
                            FirstName = "Jesper",
                            From = "Sweden",
                            LastName = "Bratt",
                            Position = "F",
                            Rank = 40,
                            Team = "NJD"
                        },
                        new
                        {
                            PlayerId = 41,
                            Age = 29,
                            FirstName = "Evgeny",
                            From = "Russia",
                            LastName = "Kuznetsov",
                            Position = "F",
                            Rank = 41,
                            Team = "WSH"
                        },
                        new
                        {
                            PlayerId = 42,
                            Age = 25,
                            FirstName = "William",
                            From = "Sweden",
                            LastName = "Nylander",
                            Position = "F",
                            Rank = 42,
                            Team = "TOR"
                        },
                        new
                        {
                            PlayerId = 43,
                            Age = 22,
                            FirstName = "Jason",
                            From = "USA",
                            LastName = "Robertson",
                            Position = "F",
                            Rank = 43,
                            Team = "DAL"
                        },
                        new
                        {
                            PlayerId = 44,
                            Age = 25,
                            FirstName = "Dylan",
                            From = "USA",
                            LastName = "Larkin",
                            Position = "F",
                            Rank = 44,
                            Team = "DET"
                        },
                        new
                        {
                            PlayerId = 45,
                            Age = 23,
                            FirstName = "Clayton",
                            From = "USA",
                            LastName = "Keller",
                            Position = "F",
                            Rank = 45,
                            Team = "ARI"
                        },
                        new
                        {
                            PlayerId = 46,
                            Age = 23,
                            FirstName = "Jordan",
                            From = "Canada",
                            LastName = "Kyrou",
                            Position = "F",
                            Rank = 46,
                            Team = "STL"
                        },
                        new
                        {
                            PlayerId = 47,
                            Age = 25,
                            FirstName = "Kevin",
                            From = "Switzerland",
                            LastName = "Fiala",
                            Position = "F",
                            Rank = 47,
                            Team = "MIN"
                        },
                        new
                        {
                            PlayerId = 48,
                            Age = 21,
                            FirstName = "Andrei",
                            From = "Russia",
                            LastName = "Svechnikov",
                            Position = "F",
                            Rank = 48,
                            Team = "CAR"
                        },
                        new
                        {
                            PlayerId = 49,
                            Age = 34,
                            FirstName = "Kristopher",
                            From = "Canada",
                            LastName = "Letang",
                            Position = "D",
                            Rank = 49,
                            Team = "PIT"
                        },
                        new
                        {
                            PlayerId = 50,
                            Age = 29,
                            FirstName = "Gabriel",
                            From = "Sweden",
                            LastName = "Landeskog",
                            Position = "F",
                            Rank = 50,
                            Team = "COL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
