// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SchoolApi.Data.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StudentsLibrary.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe5b",
                            FirstName = "Ann",
                            LastName = "Fay",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe5c",
                            FirstName = "Joe",
                            LastName = "Sun",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe5d",
                            FirstName = "Ben",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe5e",
                            FirstName = "Zoe",
                            LastName = "Cox",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe5f",
                            FirstName = "Sam",
                            LastName = "Ray",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe60",
                            FirstName = "Dan",
                            LastName = "Ash",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe61",
                            FirstName = "Pat",
                            LastName = "Lee",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe62",
                            FirstName = "Kim",
                            LastName = "Day",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe63",
                            FirstName = "Tim",
                            LastName = "Rex",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe64",
                            FirstName = "Rob",
                            LastName = "Ram",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe65",
                            FirstName = "Jan",
                            LastName = "Fry",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe66",
                            FirstName = "Jim",
                            LastName = "Tex",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe67",
                            FirstName = "Ben",
                            LastName = "Kid",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe68",
                            FirstName = "Mia",
                            LastName = "Chu",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe69",
                            FirstName = "Ted",
                            LastName = "Tao",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6a",
                            FirstName = "Amy",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6b",
                            FirstName = "Ian",
                            LastName = "Roy",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6c",
                            FirstName = "Liz",
                            LastName = "Kit",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6d",
                            FirstName = "Mat",
                            LastName = "Tan",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6e",
                            FirstName = "Deb",
                            LastName = "Roy",
                            School = "Medicine"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe6f",
                            FirstName = "Ana",
                            LastName = "Ray",
                            School = "Tourism"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe70",
                            FirstName = "Lyn",
                            LastName = "Poe",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe71",
                            FirstName = "Amy",
                            LastName = "Raj",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe72",
                            FirstName = "Kim",
                            LastName = "Ash",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe73",
                            FirstName = "Bec",
                            LastName = "Kid",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe74",
                            FirstName = "Eva",
                            LastName = "Fry",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe75",
                            FirstName = "Eli",
                            LastName = "Lap",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe76",
                            FirstName = "Sam",
                            LastName = "Yim",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe77",
                            FirstName = "Joe",
                            LastName = "Hui",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe78",
                            FirstName = "Liz",
                            LastName = "Jin",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe79",
                            FirstName = "Ric",
                            LastName = "Kuo",
                            School = "Linguistics"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7a",
                            FirstName = "Pam",
                            LastName = "Mak",
                            School = "Computing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7b",
                            FirstName = "Stu",
                            LastName = "Day",
                            School = "Business"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7c",
                            FirstName = "Tom",
                            LastName = "Gad",
                            School = "Tourism"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7d",
                            FirstName = "Bob",
                            LastName = "Bee",
                            School = "Agriculture"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7e",
                            FirstName = "Jim",
                            LastName = "Ots",
                            School = "Agriculture"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe7f",
                            FirstName = "Tom",
                            LastName = "Mag",
                            School = "Linguistics"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe80",
                            FirstName = "Hal",
                            LastName = "Doe",
                            School = "Mining"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe81",
                            FirstName = "Roy",
                            LastName = "Kim",
                            School = "Tourism"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe82",
                            FirstName = "Vis",
                            LastName = "Cox",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe83",
                            FirstName = "Kay",
                            LastName = "Aga",
                            School = "Science"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe84",
                            FirstName = "Reo",
                            LastName = "Hui",
                            School = "Nursing"
                        },
                        new
                        {
                            StudentId = "6206a1eef07a45a08420fe85",
                            FirstName = "Bob",
                            LastName = "Roe",
                            School = "Mining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
